/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.pep.visao;

import br.edu.ifsp.pep.controle.ControleSala;
import br.edu.ifsp.pep.modelo.Sala;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class Assento extends javax.swing.JDialog {

    private Sala sala;
    private ControleSala controleSala;
    private Assento selecionado;
    
    /**
     * Creates new form Assento
     */
    public Assento(java.awt.Frame parent, boolean modal, Sala s) {
        super(parent, modal);
        initComponents();
        this.sala = s;
        this.controleSala = new ControleSala();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfLetra = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        tfCodigo = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        mbCadastrar = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        mbCadastrar1 = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tfLetra.setLabel("Leta do assento");

        tfCodigo.setLabel("Número do assento");

        mbCadastrar.setBackground(new java.awt.Color(73, 136, 137));
        mbCadastrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mbCadastrar.setText("Cadastrar");
        mbCadastrar.setEndColor(new java.awt.Color(73, 136, 137));
        mbCadastrar.setHoverEndColor(new java.awt.Color(37, 157, 218));
        mbCadastrar.setHoverStartColor(new java.awt.Color(37, 157, 218));
        mbCadastrar.setMaximumSize(new java.awt.Dimension(64, 19));
        mbCadastrar.setMinimumSize(new java.awt.Dimension(64, 19));
        mbCadastrar.setSelectedColor(new java.awt.Color(37, 157, 218));
        mbCadastrar.setStartColor(new java.awt.Color(73, 136, 137));
        mbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbCadastrarActionPerformed(evt);
            }
        });
        mbCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mbCadastrarKeyPressed(evt);
            }
        });

        mbCadastrar1.setBackground(new java.awt.Color(73, 136, 137));
        mbCadastrar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mbCadastrar1.setText("Cancelar");
        mbCadastrar1.setEndColor(new java.awt.Color(73, 136, 137));
        mbCadastrar1.setHoverEndColor(new java.awt.Color(37, 157, 218));
        mbCadastrar1.setHoverStartColor(new java.awt.Color(37, 157, 218));
        mbCadastrar1.setMaximumSize(new java.awt.Dimension(64, 19));
        mbCadastrar1.setMinimumSize(new java.awt.Dimension(64, 19));
        mbCadastrar1.setSelectedColor(new java.awt.Color(37, 157, 218));
        mbCadastrar1.setStartColor(new java.awt.Color(73, 136, 137));
        mbCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbCadastrar1ActionPerformed(evt);
            }
        });
        mbCadastrar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mbCadastrar1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(mbCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbCadastrarActionPerformed
        try{
            Integer codigo = Integer.parseInt(tfCodigo.getText().trim());
//            char letra = tfLetra.getText().trim();
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Insira apenas numeros no codigo do assendo");
        }
    }//GEN-LAST:event_mbCadastrarActionPerformed

    private void mbCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mbCadastrarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbCadastrarKeyPressed

    private void mbCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbCadastrar1ActionPerformed
        dispose();
    }//GEN-LAST:event_mbCadastrar1ActionPerformed

    private void mbCadastrar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mbCadastrar1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbCadastrar1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Assento dialog = new Assento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton mbCadastrar;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton mbCadastrar1;
    private com.hq.swingmaterialdesign.materialdesign.MTextField tfCodigo;
    private com.hq.swingmaterialdesign.materialdesign.MTextField tfLetra;
    // End of variables declaration//GEN-END:variables
}
