/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.pep.visao;

import br.edu.ifsp.pep.controle.ControleGenero;
import br.edu.ifsp.pep.controle.ControleSala;
import br.edu.ifsp.pep.modelo.Genero;
import br.edu.ifsp.pep.modelo.Sala;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class CadastroGenero extends javax.swing.JDialog {

    private ControleGenero controleGenero;
    private Genero selecionado;
    
    /**
     * Creates new form CadastroSala
     */
    public CadastroGenero(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.controleGenero = new ControleGenero();
    }
    
    public void setSelecionado(Genero g){
        this.selecionado = g;
        tfDescricao.setText(g.getDescricao());
        mbCadastrar.setText("Salvar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfDescricao = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        jLabel1 = new javax.swing.JLabel();
        mbCadastrar = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        mbCancelar = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);

        tfDescricao.setLabel("Descrição");

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro Genero");

        mbCadastrar.setBackground(new java.awt.Color(73, 136, 137));
        mbCadastrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mbCadastrar.setText("Cadastrar");
        mbCadastrar.setEndColor(new java.awt.Color(73, 136, 137));
        mbCadastrar.setHoverEndColor(new java.awt.Color(37, 157, 218));
        mbCadastrar.setHoverStartColor(new java.awt.Color(37, 157, 218));
        mbCadastrar.setMaximumSize(new java.awt.Dimension(64, 19));
        mbCadastrar.setMinimumSize(new java.awt.Dimension(64, 19));
        mbCadastrar.setSelectedColor(new java.awt.Color(37, 157, 218));
        mbCadastrar.setStartColor(new java.awt.Color(73, 136, 137));
        mbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbCadastrarActionPerformed(evt);
            }
        });
        mbCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mbCadastrarKeyPressed(evt);
            }
        });

        mbCancelar.setBackground(new java.awt.Color(73, 136, 137));
        mbCancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mbCancelar.setText("Cancelar");
        mbCancelar.setEndColor(new java.awt.Color(73, 136, 137));
        mbCancelar.setHoverEndColor(new java.awt.Color(37, 157, 218));
        mbCancelar.setHoverStartColor(new java.awt.Color(37, 157, 218));
        mbCancelar.setMaximumSize(new java.awt.Dimension(64, 19));
        mbCancelar.setMinimumSize(new java.awt.Dimension(64, 19));
        mbCancelar.setSelectedColor(new java.awt.Color(37, 157, 218));
        mbCancelar.setStartColor(new java.awt.Color(73, 136, 137));
        mbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbCancelarActionPerformed(evt);
            }
        });
        mbCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mbCancelarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(mbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mbCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(mbCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbCadastrarActionPerformed
        String descricao = tfDescricao.getText().trim();
        if(!descricao.isEmpty()){
        Genero g = new Genero(descricao);
            if(this.selecionado == null){
                controleGenero.persist(g);
                JOptionPane.showMessageDialog(null, "Gênero cadastrado");
                dispose();
            }else{
                g.setCodigo(this.selecionado.getCodigo());
                controleGenero.merge(g);
                JOptionPane.showMessageDialog(null, "Gênero modificado");
                dispose();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Preencha o campo!");
        }
    }//GEN-LAST:event_mbCadastrarActionPerformed

    private void mbCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mbCadastrarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbCadastrarKeyPressed

    private void mbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_mbCancelarActionPerformed

    private void mbCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mbCancelarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbCancelarKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton mbCadastrar;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton mbCancelar;
    private com.hq.swingmaterialdesign.materialdesign.MTextField tfDescricao;
    // End of variables declaration//GEN-END:variables
}
