/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.pep.visao;

import br.edu.ifsp.pep.controle.ControleSala;
import br.edu.ifsp.pep.modelo.Sala;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class CadastroSala extends javax.swing.JDialog {

    private ControleSala controleSala;
    private Sala selecionado;
    
    /**
     * Creates new form CadastroSala
     */
    public CadastroSala(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.controleSala = new ControleSala();
    }
    
    public void setSelecionado(Sala s){
        this.selecionado = s;
        tfQuantidadeAssento.setText(String.valueOf(s.getQtdAssendo()));
        cbDisponivel.setSelected(s.isDisponivel());
        mbCadastrar.setText("Salvar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfQuantidadeAssento = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        cbDisponivel = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        mbCadastrar = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        mbCancelar = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);

        tfQuantidadeAssento.setLabel("QuantidadeAssento");

        cbDisponivel.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        cbDisponivel.setText("Disponível");

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro Sala");

        mbCadastrar.setBackground(new java.awt.Color(73, 136, 137));
        mbCadastrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mbCadastrar.setText("Cadastrar");
        mbCadastrar.setEndColor(new java.awt.Color(73, 136, 137));
        mbCadastrar.setHoverEndColor(new java.awt.Color(37, 157, 218));
        mbCadastrar.setHoverStartColor(new java.awt.Color(37, 157, 218));
        mbCadastrar.setMaximumSize(new java.awt.Dimension(64, 19));
        mbCadastrar.setMinimumSize(new java.awt.Dimension(64, 19));
        mbCadastrar.setSelectedColor(new java.awt.Color(37, 157, 218));
        mbCadastrar.setStartColor(new java.awt.Color(73, 136, 137));
        mbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbCadastrarActionPerformed(evt);
            }
        });
        mbCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mbCadastrarKeyPressed(evt);
            }
        });

        mbCancelar.setBackground(new java.awt.Color(73, 136, 137));
        mbCancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mbCancelar.setText("Cancelar");
        mbCancelar.setEndColor(new java.awt.Color(73, 136, 137));
        mbCancelar.setHoverEndColor(new java.awt.Color(37, 157, 218));
        mbCancelar.setHoverStartColor(new java.awt.Color(37, 157, 218));
        mbCancelar.setMaximumSize(new java.awt.Dimension(64, 19));
        mbCancelar.setMinimumSize(new java.awt.Dimension(64, 19));
        mbCancelar.setSelectedColor(new java.awt.Color(37, 157, 218));
        mbCancelar.setStartColor(new java.awt.Color(73, 136, 137));
        mbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbCancelarActionPerformed(evt);
            }
        });
        mbCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mbCancelarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfQuantidadeAssento, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbDisponivel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addComponent(mbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfQuantidadeAssento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(cbDisponivel)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mbCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(mbCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbCadastrarActionPerformed
        try{
            Integer quantidade = Integer.parseInt(tfQuantidadeAssento.getText().trim());
            boolean disponivel = cbDisponivel.isSelected();
            Sala sala = new Sala(disponivel, quantidade);
            if(this.selecionado == null){
                controleSala.persist(sala);
                JOptionPane.showMessageDialog(null, "Sala cadastrada");
                dispose();
            }else{
                sala.setCodigo(this.selecionado.getCodigo());
                controleSala.merge(sala);
                JOptionPane.showMessageDialog(null, "Sala modificada");
                dispose();
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Insira apenas números na quantidade!");
        }
    }//GEN-LAST:event_mbCadastrarActionPerformed

    private void mbCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mbCadastrarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbCadastrarKeyPressed

    private void mbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_mbCancelarActionPerformed

    private void mbCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mbCancelarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbCancelarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroSala dialog = new CadastroSala(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbDisponivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton mbCadastrar;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton mbCancelar;
    private com.hq.swingmaterialdesign.materialdesign.MTextField tfQuantidadeAssento;
    // End of variables declaration//GEN-END:variables
}
