/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.pep.visao;

import br.edu.ifsp.pep.controle.ControleGenero;
import br.edu.ifsp.pep.controle.ControleSala;
import br.edu.ifsp.pep.modelo.Genero;
import br.edu.ifsp.pep.modelo.Sala;
import java.util.List;
import javax.persistence.NoResultException;
import javax.persistence.RollbackException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pedro
 */
public class GerenciarGenero extends javax.swing.JDialog {

    private List<Genero> listaGenero;
    private ControleGenero controleGenero;
    
    /**
     * Creates new form GerenciarSalas
     */
    public GerenciarGenero(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.controleGenero = new ControleGenero();
        this.listaGenero = this.controleGenero.findAll();
        atualizarGenero();
    }

    private void atualizarGenero(){
        DefaultTableModel modelo = (DefaultTableModel) tbGeneros.getModel();
        modelo.setNumRows(0);
        for(Genero g: this.listaGenero){
            modelo.addRow(new Object[] {g.getCodigo(), g.getDescricao()});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbGeneros = new javax.swing.JTable();
        tfPesquisar = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        mbConcluir = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        mbPesquisar = new com.hq.swingmaterialdesign.materialdesign.MButton();
        mbAdicionar = new com.hq.swingmaterialdesign.materialdesign.MButton();
        mbEditar = new com.hq.swingmaterialdesign.materialdesign.MButton();
        mbRemover = new com.hq.swingmaterialdesign.materialdesign.MButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);

        tbGeneros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbGeneros.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tbGeneros);
        tbGeneros.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        tfPesquisar.setLabel("Pesquisa");
        tfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesquisarActionPerformed(evt);
            }
        });

        mbConcluir.setBackground(new java.awt.Color(73, 136, 137));
        mbConcluir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mbConcluir.setText("Concluir");
        mbConcluir.setEndColor(new java.awt.Color(73, 136, 137));
        mbConcluir.setHoverEndColor(new java.awt.Color(37, 157, 218));
        mbConcluir.setHoverStartColor(new java.awt.Color(37, 157, 218));
        mbConcluir.setMaximumSize(new java.awt.Dimension(64, 19));
        mbConcluir.setMinimumSize(new java.awt.Dimension(64, 19));
        mbConcluir.setSelectedColor(new java.awt.Color(37, 157, 218));
        mbConcluir.setStartColor(new java.awt.Color(73, 136, 137));
        mbConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbConcluirActionPerformed(evt);
            }
        });
        mbConcluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mbConcluirKeyPressed(evt);
            }
        });

        mbPesquisar.setBackground(new java.awt.Color(73, 136, 137));
        mbPesquisar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mbPesquisar.setText("Pesquisar");
        mbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbPesquisarActionPerformed(evt);
            }
        });

        mbAdicionar.setBackground(new java.awt.Color(73, 136, 137));
        mbAdicionar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mbAdicionar.setText("Adicionar");
        mbAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbAdicionarActionPerformed(evt);
            }
        });

        mbEditar.setBackground(new java.awt.Color(73, 136, 137));
        mbEditar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mbEditar.setText("Editar");
        mbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbEditarActionPerformed(evt);
            }
        });

        mbRemover.setBackground(new java.awt.Color(73, 136, 137));
        mbRemover.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mbRemover.setText("Remover");
        mbRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mbPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mbConcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mbAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mbRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbConcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mbAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesquisarActionPerformed

    private void mbConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbConcluirActionPerformed
        dispose();
    }//GEN-LAST:event_mbConcluirActionPerformed

    private void mbConcluirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mbConcluirKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbConcluirKeyPressed

    private void mbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbPesquisarActionPerformed
        if(tfPesquisar.getText().trim().isEmpty()){
            this.listaGenero = controleGenero.findAll();
            atualizarGenero();
        }else{
            try{
                Integer codigo = Integer.parseInt(tfPesquisar.getText().trim());
                Genero g = controleGenero.findByCodigo(codigo);
                this.listaGenero.clear();
                this.listaGenero.add(g);
                atualizarGenero();
            }catch(NoResultException ex){
                JOptionPane.showMessageDialog(null, "Não foi possivel encontrar esse genero");
            }
        }
    }//GEN-LAST:event_mbPesquisarActionPerformed

    private void mbAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbAdicionarActionPerformed
        CadastroSala cs = new CadastroSala(null, true);
        cs.setModal(true);
        cs.setVisible(true);
        this.listaGenero = controleGenero.findAll();
        atualizarGenero();
    }//GEN-LAST:event_mbAdicionarActionPerformed

    private void mbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbEditarActionPerformed
        int row = tbGeneros.getSelectedRow();
        if(row > -1){
            try{
                Integer cod = (Integer) tbGeneros.getValueAt(row, 0);
                Genero g = controleGenero.findByCodigo(cod);
                CadastroGenero cs = new CadastroGenero(null, true);
                cs.setModal(true);
                cs.setSelecionado(g);
                cs.setVisible(true);
                this.listaGenero = controleGenero.findAll();
                atualizarGenero();
            }catch(NoResultException ex){
                JOptionPane.showMessageDialog(null, "Nenhuma sala encontrada com esse código");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma sala abaixo para editar!");
        }
    }//GEN-LAST:event_mbEditarActionPerformed

    private void mbRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbRemoverActionPerformed
        int row = tbGeneros.getSelectedRow();
        if(row > -1){
            try{
                Integer codigo = (Integer) tbGeneros.getValueAt(row, 0);
                Genero g = controleGenero.findByCodigo(codigo);
                controleGenero.remove(g);
                this.listaGenero = controleGenero.findAll();
                atualizarGenero();
            }catch(RollbackException ex){
                JOptionPane.showMessageDialog(null, "Não é possivel excluir essa sala");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma sala para remover");
        }
    }//GEN-LAST:event_mbRemoverActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.hq.swingmaterialdesign.materialdesign.MButton mbAdicionar;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton mbConcluir;
    private com.hq.swingmaterialdesign.materialdesign.MButton mbEditar;
    private com.hq.swingmaterialdesign.materialdesign.MButton mbPesquisar;
    private com.hq.swingmaterialdesign.materialdesign.MButton mbRemover;
    private javax.swing.JTable tbGeneros;
    private com.hq.swingmaterialdesign.materialdesign.MTextField tfPesquisar;
    // End of variables declaration//GEN-END:variables
}
