/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.pep.visao;

import br.edu.ifsp.pep.controle.ControleSala;
import br.edu.ifsp.pep.modelo.Sala;
import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import java.util.List;
import javax.persistence.NoResultException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pedro
 */
public class GerenciarSalas extends javax.swing.JDialog {

    private List<Sala> listaSalas;
    private ControleSala controleSala;
    
    /**
     * Creates new form GerenciarSalas
     */
    public GerenciarSalas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.controleSala = new ControleSala();
        this.listaSalas = this.controleSala.findAll();
        atualizarSalas();
    }

    private void atualizarSalas(){
        DefaultTableModel modelo = (DefaultTableModel) tbSala.getModel();
        modelo.setNumRows(0);
        for(Sala s: this.listaSalas){
            modelo.addRow(new Object[] {s.getCodigo(), s.isDisponivel(),s.getQtdAssendo()});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSala = new javax.swing.JTable();
        tfPesquisar = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        mbAdicionarIngressoVenda = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        mbRemoverIngressoVenda = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        mbRemoverIngressoVenda1 = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        mbAdicionarIngressoVenda1 = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);

        tbSala.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Disponível", "Assentos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSala.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tbSala);
        tbSala.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        tfPesquisar.setLabel("Pesquisa");
        tfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesquisarActionPerformed(evt);
            }
        });

        mbAdicionarIngressoVenda.setBackground(new java.awt.Color(73, 136, 137));
        mbAdicionarIngressoVenda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mbAdicionarIngressoVenda.setText("Adicionar");
        mbAdicionarIngressoVenda.setEndColor(new java.awt.Color(73, 136, 137));
        mbAdicionarIngressoVenda.setHoverEndColor(new java.awt.Color(37, 157, 218));
        mbAdicionarIngressoVenda.setHoverStartColor(new java.awt.Color(37, 157, 218));
        mbAdicionarIngressoVenda.setMaximumSize(new java.awt.Dimension(64, 19));
        mbAdicionarIngressoVenda.setMinimumSize(new java.awt.Dimension(64, 19));
        mbAdicionarIngressoVenda.setSelectedColor(new java.awt.Color(37, 157, 218));
        mbAdicionarIngressoVenda.setStartColor(new java.awt.Color(73, 136, 137));
        mbAdicionarIngressoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbAdicionarIngressoVendaActionPerformed(evt);
            }
        });
        mbAdicionarIngressoVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mbAdicionarIngressoVendaKeyPressed(evt);
            }
        });

        mbRemoverIngressoVenda.setBackground(new java.awt.Color(73, 136, 137));
        mbRemoverIngressoVenda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mbRemoverIngressoVenda.setText("REMOVER");
        mbRemoverIngressoVenda.setEndColor(new java.awt.Color(73, 136, 137));
        mbRemoverIngressoVenda.setHoverEndColor(new java.awt.Color(37, 157, 218));
        mbRemoverIngressoVenda.setHoverStartColor(new java.awt.Color(37, 157, 218));
        mbRemoverIngressoVenda.setMaximumSize(new java.awt.Dimension(64, 19));
        mbRemoverIngressoVenda.setMinimumSize(new java.awt.Dimension(64, 19));
        mbRemoverIngressoVenda.setSelectedColor(new java.awt.Color(37, 157, 218));
        mbRemoverIngressoVenda.setStartColor(new java.awt.Color(73, 136, 137));
        mbRemoverIngressoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbRemoverIngressoVendaActionPerformed(evt);
            }
        });
        mbRemoverIngressoVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mbRemoverIngressoVendaKeyPressed(evt);
            }
        });

        mbRemoverIngressoVenda1.setBackground(new java.awt.Color(73, 136, 137));
        mbRemoverIngressoVenda1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mbRemoverIngressoVenda1.setText("Editar");
        mbRemoverIngressoVenda1.setEndColor(new java.awt.Color(73, 136, 137));
        mbRemoverIngressoVenda1.setHoverEndColor(new java.awt.Color(37, 157, 218));
        mbRemoverIngressoVenda1.setHoverStartColor(new java.awt.Color(37, 157, 218));
        mbRemoverIngressoVenda1.setMaximumSize(new java.awt.Dimension(64, 19));
        mbRemoverIngressoVenda1.setMinimumSize(new java.awt.Dimension(64, 19));
        mbRemoverIngressoVenda1.setSelectedColor(new java.awt.Color(37, 157, 218));
        mbRemoverIngressoVenda1.setStartColor(new java.awt.Color(73, 136, 137));
        mbRemoverIngressoVenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbRemoverIngressoVenda1ActionPerformed(evt);
            }
        });
        mbRemoverIngressoVenda1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mbRemoverIngressoVenda1KeyPressed(evt);
            }
        });

        mbAdicionarIngressoVenda1.setBackground(new java.awt.Color(73, 136, 137));
        mbAdicionarIngressoVenda1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mbAdicionarIngressoVenda1.setText("Pesquisar");
        mbAdicionarIngressoVenda1.setEndColor(new java.awt.Color(73, 136, 137));
        mbAdicionarIngressoVenda1.setHoverEndColor(new java.awt.Color(37, 157, 218));
        mbAdicionarIngressoVenda1.setHoverStartColor(new java.awt.Color(37, 157, 218));
        mbAdicionarIngressoVenda1.setMaximumSize(new java.awt.Dimension(64, 19));
        mbAdicionarIngressoVenda1.setMinimumSize(new java.awt.Dimension(64, 19));
        mbAdicionarIngressoVenda1.setSelectedColor(new java.awt.Color(37, 157, 218));
        mbAdicionarIngressoVenda1.setStartColor(new java.awt.Color(73, 136, 137));
        mbAdicionarIngressoVenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbAdicionarIngressoVenda1ActionPerformed(evt);
            }
        });
        mbAdicionarIngressoVenda1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mbAdicionarIngressoVenda1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mbAdicionarIngressoVenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mbAdicionarIngressoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mbRemoverIngressoVenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mbRemoverIngressoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbAdicionarIngressoVenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mbAdicionarIngressoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbRemoverIngressoVenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbRemoverIngressoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesquisarActionPerformed

    private void mbAdicionarIngressoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbAdicionarIngressoVendaActionPerformed
        CadastroSala cs = new CadastroSala(null, true);
        cs.setModal(true);
        cs.setVisible(true);
        this.listaSalas = controleSala.findAll();
        atualizarSalas();
    }//GEN-LAST:event_mbAdicionarIngressoVendaActionPerformed

    private void mbAdicionarIngressoVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mbAdicionarIngressoVendaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbAdicionarIngressoVendaKeyPressed

    private void mbRemoverIngressoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbRemoverIngressoVendaActionPerformed
        int row = tbSala.getSelectedRow();
        if(row > -1){
            Integer codigo = (Integer) tbSala.getValueAt(row, 0);
            Sala s = controleSala.findByCodigo(codigo);
            controleSala.remove(s);
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma sala para remover");
        }
    }//GEN-LAST:event_mbRemoverIngressoVendaActionPerformed

    private void mbRemoverIngressoVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mbRemoverIngressoVendaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbRemoverIngressoVendaKeyPressed

    private void mbRemoverIngressoVenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbRemoverIngressoVenda1ActionPerformed
        int row = tbSala.getSelectedRow();
        if(row > -1){
            try{
                Integer cod = (Integer) tbSala.getValueAt(row, 0);
                Sala s = controleSala.findByCodigo(cod);
                CadastroSala cs = new CadastroSala(null, true);
                cs.setModal(true);
                cs.setSelecionado(s);
                cs.setVisible(true);
                this.listaSalas = controleSala.findAll();
                atualizarSalas();
            }catch(NoResultException ex){
                JOptionPane.showMessageDialog(null, "Nenhuma sala encontrada com esse código");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma sala abaixo para editar!");
        }
    }//GEN-LAST:event_mbRemoverIngressoVenda1ActionPerformed

    private void mbRemoverIngressoVenda1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mbRemoverIngressoVenda1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbRemoverIngressoVenda1KeyPressed

    private void mbAdicionarIngressoVenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbAdicionarIngressoVenda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbAdicionarIngressoVenda1ActionPerformed

    private void mbAdicionarIngressoVenda1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mbAdicionarIngressoVenda1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbAdicionarIngressoVenda1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GerenciarSalas dialog = new GerenciarSalas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton mbAdicionarIngressoVenda;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton mbAdicionarIngressoVenda1;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton mbRemoverIngressoVenda;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton mbRemoverIngressoVenda1;
    private javax.swing.JTable tbSala;
    private com.hq.swingmaterialdesign.materialdesign.MTextField tfPesquisar;
    // End of variables declaration//GEN-END:variables
}
