/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.pep.visao;

import br.edu.ifsp.pep.controle.ControleFilme;
import br.edu.ifsp.pep.controle.ControleItem;
import br.edu.ifsp.pep.controle.ControleProduto;
import br.edu.ifsp.pep.modelo.Combo;
import br.edu.ifsp.pep.modelo.Filme;
import br.edu.ifsp.pep.modelo.Item;
import br.edu.ifsp.pep.modelo.Produto;
import br.edu.ifsp.pep.modelo.Usuario;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.persistence.NoResultException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pedro
 */
public class MenuComum extends javax.swing.JFrame {
    
    private List<Item> listaItens;
    private List<Filme> listaFilmes;
    
    private Usuario usuario;
    private ControleItem controleI;
    private ControleProduto controleP;
    private ControleFilme controleF;
    
    public MenuComum(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        this.labelBoasVindas.setText("Bem-vindo, " + usuario.getNome() + "!");
        this.setResizable(false);
        this.controleI = new ControleItem();
        this.controleP = new ControleProduto();
        this.controleF = new ControleFilme();
        
        mbSessoes.setSelected(false);
        jpSessoes.setVisible(false);
        
        mbVendas.setSelected(false);
        jpVenda.setVisible(false);
        
        mBHome.setSelected(true);
        jpHome.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */ 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PMain = new javax.swing.JPanel();
        jpMenu = new javax.swing.JPanel();
        lbMenu = new javax.swing.JLabel();
        mBHome = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        mbSair = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        mbVendas = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        mbSessoes = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        jpPrincipal = new javax.swing.JPanel();
        jpVenda = new javax.swing.JPanel();
        jpHome = new javax.swing.JPanel();
        labelBoasVindas = new javax.swing.JLabel();
        jpSessoes = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(960, 720));

        PMain.setBackground(java.awt.Color.white);
        PMain.setPreferredSize(new java.awt.Dimension(960, 720));

        jpMenu.setBackground(new java.awt.Color(73, 136, 137));
        jpMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lbMenu.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lbMenu.setText("SGC");

        mBHome.setBackground(new java.awt.Color(73, 136, 137));
        mBHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mBHome.setText("Home");
        mBHome.setEndColor(new java.awt.Color(73, 136, 137));
        mBHome.setFocusPainted(false);
        mBHome.setHoverEndColor(new java.awt.Color(37, 157, 218));
        mBHome.setHoverStartColor(new java.awt.Color(37, 157, 218));
        mBHome.setSelected(true);
        mBHome.setSelectedColor(new java.awt.Color(37, 157, 218));
        mBHome.setStartColor(new java.awt.Color(73, 136, 137));
        mBHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBHomeActionPerformed(evt);
            }
        });

        mbSair.setBackground(new java.awt.Color(73, 136, 137));
        mbSair.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mbSair.setText("Sair");
        mbSair.setEndColor(new java.awt.Color(73, 136, 137));
        mbSair.setHoverEndColor(new java.awt.Color(37, 157, 218));
        mbSair.setHoverStartColor(new java.awt.Color(37, 157, 218));
        mbSair.setSelectedColor(new java.awt.Color(37, 157, 218));
        mbSair.setStartColor(new java.awt.Color(73, 136, 137));
        mbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbSairActionPerformed(evt);
            }
        });
        mbSair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mbSairKeyPressed(evt);
            }
        });

        mbVendas.setBackground(new java.awt.Color(73, 136, 137));
        mbVendas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mbVendas.setText("Vendas");
        mbVendas.setEndColor(new java.awt.Color(73, 136, 137));
        mbVendas.setHoverEndColor(new java.awt.Color(37, 157, 218));
        mbVendas.setHoverStartColor(new java.awt.Color(37, 157, 218));
        mbVendas.setSelectedColor(new java.awt.Color(37, 157, 218));
        mbVendas.setStartColor(new java.awt.Color(73, 136, 137));
        mbVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbVendasActionPerformed(evt);
            }
        });

        mbSessoes.setBackground(new java.awt.Color(73, 136, 137));
        mbSessoes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mbSessoes.setText("SESSÕES");
        mbSessoes.setEndColor(new java.awt.Color(73, 136, 137));
        mbSessoes.setHoverEndColor(new java.awt.Color(37, 157, 218));
        mbSessoes.setHoverStartColor(new java.awt.Color(37, 157, 218));
        mbSessoes.setSelectedColor(new java.awt.Color(37, 157, 218));
        mbSessoes.setStartColor(new java.awt.Color(73, 136, 137));
        mbSessoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbSessoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mBHome, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbSessoes, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lbMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbMenu)
                .addGap(108, 108, 108)
                .addComponent(mBHome, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mbVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mbSessoes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpPrincipal.setBackground(java.awt.Color.white);

        jpVenda.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout jpVendaLayout = new javax.swing.GroupLayout(jpVenda);
        jpVenda.setLayout(jpVendaLayout);
        jpVendaLayout.setHorizontalGroup(
            jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        jpVendaLayout.setVerticalGroup(
            jpVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1032, Short.MAX_VALUE)
        );

        jpHome.setBackground(java.awt.Color.white);

        labelBoasVindas.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        labelBoasVindas.setText("Bem vindo, usuário !");

        javax.swing.GroupLayout jpHomeLayout = new javax.swing.GroupLayout(jpHome);
        jpHome.setLayout(jpHomeLayout);
        jpHomeLayout.setHorizontalGroup(
            jpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBoasVindas)
                .addContainerGap(572, Short.MAX_VALUE))
        );
        jpHomeLayout.setVerticalGroup(
            jpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBoasVindas)
                .addContainerGap(994, Short.MAX_VALUE))
        );

        jpSessoes.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout jpSessoesLayout = new javax.swing.GroupLayout(jpSessoes);
        jpSessoes.setLayout(jpSessoesLayout);
        jpSessoesLayout.setHorizontalGroup(
            jpSessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
        );
        jpSessoesLayout.setVerticalGroup(
            jpSessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1032, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
            .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpSessoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1057, Short.MAX_VALUE)
            .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpSessoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PMainLayout = new javax.swing.GroupLayout(PMain);
        PMain.setLayout(PMainLayout);
        PMainLayout.setHorizontalGroup(
            PMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMainLayout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PMainLayout.setVerticalGroup(
            PMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMainLayout.createSequentialGroup()
                .addGroup(PMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PMain, javax.swing.GroupLayout.PREFERRED_SIZE, 993, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1057, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mbSairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mbSairKeyPressed
    }//GEN-LAST:event_mbSairKeyPressed

    private void mbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbSairActionPerformed
        dispose();
    }//GEN-LAST:event_mbSairActionPerformed

    private void mBHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBHomeActionPerformed
        mbSessoes.setSelected(false);
        jpSessoes.setVisible(false);
        
        mbVendas.setSelected(false);
        jpVenda.setVisible(false);
        
        mBHome.setSelected(true);
        jpHome.setVisible(true);
    }//GEN-LAST:event_mBHomeActionPerformed

    private void mbVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbVendasActionPerformed
        mbSessoes.setSelected(false);
        jpSessoes.setVisible(false);
        
        mbVendas.setSelected(true);
        jpVenda.setVisible(true);
        
        mBHome.setSelected(false);
        jpHome.setVisible(false); 
    }//GEN-LAST:event_mbVendasActionPerformed

    private void mbSessoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbSessoesActionPerformed
        mbSessoes.setSelected(true);
        jpSessoes.setVisible(true);
        
        mbVendas.setSelected(false);
        jpVenda.setVisible(false);
        
        mBHome.setSelected(false);
        jpHome.setVisible(false); 
    }//GEN-LAST:event_mbSessoesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PMain;
    private javax.swing.JPanel jpHome;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JPanel jpSessoes;
    private javax.swing.JPanel jpVenda;
    private javax.swing.JLabel labelBoasVindas;
    private javax.swing.JLabel lbMenu;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton mBHome;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton mbSair;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton mbSessoes;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton mbVendas;
    // End of variables declaration//GEN-END:variables
}
