/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.pep.visao;

import br.edu.ifsp.pep.relatorio.GerarRelatorio;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class TelaRelatorio extends javax.swing.JDialog {
    private GerarRelatorio gerador = new GerarRelatorio();
    
    public TelaRelatorio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgOpcoes = new javax.swing.ButtonGroup();
        jpPrincipal = new javax.swing.JPanel();
        mbSair = new com.hq.swingmaterialdesign.materialdesign.MButton();
        mbGerar = new com.hq.swingmaterialdesign.materialdesign.MButton();
        tfDataInicial = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        tfDataFinal = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        jrbOpcaoVenda = new javax.swing.JRadioButton();
        jrbOpcaoSessao = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpPrincipal.setBackground(java.awt.Color.white);
        jpPrincipal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jpPrincipal.setPreferredSize(new java.awt.Dimension(410, 360));

        mbSair.setBackground(new java.awt.Color(73, 136, 137));
        mbSair.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mbSair.setText("Sair");
        mbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbSairActionPerformed(evt);
            }
        });

        mbGerar.setBackground(new java.awt.Color(73, 136, 137));
        mbGerar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mbGerar.setText("Gerar");
        mbGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbGerarActionPerformed(evt);
            }
        });

        tfDataInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        tfDataInicial.setLabel("Data inicial");
        tfDataInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataInicialActionPerformed(evt);
            }
        });

        tfDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        tfDataFinal.setLabel("Data final");
        tfDataFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataFinalActionPerformed(evt);
            }
        });

        bgOpcoes.add(jrbOpcaoVenda);
        jrbOpcaoVenda.setText("Relatório de vendas");
        jrbOpcaoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOpcaoVendaActionPerformed(evt);
            }
        });

        bgOpcoes.add(jrbOpcaoSessao);
        jrbOpcaoSessao.setText("Relatório de sessões");

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrincipalLayout.createSequentialGroup()
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrincipalLayout.createSequentialGroup()
                                .addComponent(tfDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addComponent(jrbOpcaoVenda)
                                .addGap(57, 57, 57)))
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbOpcaoSessao)
                            .addComponent(tfDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrincipalLayout.createSequentialGroup()
                        .addComponent(mbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mbGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbOpcaoVenda)
                    .addComponent(jrbOpcaoSessao))
                .addGap(28, 28, 28)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mbGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(233, 233, 233))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbSairActionPerformed
        dispose();
    }//GEN-LAST:event_mbSairActionPerformed

    private void mbGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbGerarActionPerformed
        try{
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date dataInicial = sdf.parse(tfDataInicial.getText());
            Date dataFinal = sdf.parse(tfDataFinal.getText());
            
            EntityManager em = Persistence.createEntityManagerFactory("SGCPU")
                    .createEntityManager();

            if(jrbOpcaoSessao.isSelected()){
                gerador.gerarSessao(em, "RelatorioSessao.jasper", dataInicial, dataFinal);
                this.dispose();
            }else if(jrbOpcaoVenda.isSelected()){
                gerador.gerarSessao(em, "RelatorioProduto.jasper", dataInicial, dataFinal);
                this.dispose();
            }else{                        
                JOptionPane.showMessageDialog(null, "Selecione uma opção de relatório!");
            } 
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Insira uma data válida no formato dd/mm/aaaa!");
        }
        
    }//GEN-LAST:event_mbGerarActionPerformed

    private void tfDataInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataInicialActionPerformed

    private void tfDataFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataFinalActionPerformed

    private void jrbOpcaoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOpcaoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbOpcaoVendaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgOpcoes;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JRadioButton jrbOpcaoSessao;
    private javax.swing.JRadioButton jrbOpcaoVenda;
    private com.hq.swingmaterialdesign.materialdesign.MButton mbGerar;
    private com.hq.swingmaterialdesign.materialdesign.MButton mbSair;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField tfDataFinal;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField tfDataInicial;
    // End of variables declaration//GEN-END:variables
}
